version: '2.1'
services:
  broker:
    container_name: mayan-edms-broker
    image: healthcheck/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: mayan
      RABBITMQ_DEFAULT_PASS: mayan
      RABBITMQ_DEFAULT_VHOST: mayan
    volumes:
      - /opt/mediadepot/apps/mayan/rabbitmq:/var/lib/rabbitmq
    networks:
      - mayan

  results:
    container_name: mayan-edms-results
    image: healthcheck/redis
    volumes:
      - /opt/mediadepot/apps/mayan/results:/data
    networks:
      - mayan

  db:
    container_name: mayan-edms-db
    image: healthcheck/postgres
    environment:
      POSTGRES_DB: mayan
      POSTGRES_PASSWORD: mayan-password
      POSTGRES_USER: mayan
    volumes:
      - /opt/mediadepot/apps/mayan/db:/var/lib/postgresql/data
    networks:
      - mayan

  mayan-edms:
    container_name: mayan-edms-app
    image: mediadepot/mayan:latest
#    image: mayanedms/mayanedms:latest
    links:
    - db
    - results
    - broker
    depends_on:
      broker:
        condition: service_healthy
      db:
        condition: service_healthy
      results:
        condition: service_healthy
    environment:
      MAYAN_BROKER_URL: amqp://mayan:mayan@broker:5672/mayan
      MAYAN_CELERY_RESULT_BACKEND: redis://results:6379/0
      MAYAN_DATABASE_HOST: db
      MAYAN_DATABASE_NAME: mayan
      MAYAN_DATABASE_PASSWORD: mayan-password
      MAYAN_DATABASE_USER: mayan
      MAYAN_PIP_INSTALLS: "requests"
#      MAYAN_DATABASE_CONN_MAX_AGE: 60

      # Mayan 2
      # MAYAN_DATABASE_DRIVER: django.db.backends.postgres  # for mayan 2.x

      # Mayan 3
      MAYAN_DATABASE_ENGINE: django.db.backends.postgresql # for mayan 3.x

    ports:
#      - 80 # 80 is default port for Mayan 2.7
      - 8000 # 8000 is default port for Mayan v3.x and above
    volumes:
      - /opt/mediadepot/apps/mayan/config:/var/lib/mayan/system
#      - app:/var/lib/mayan # NOTE: doing this will result in missing config files, causing mayan to fail to start.
      - /media/temp/blackhole/documents:/blackhole
      - /media/storage/documents:/documents
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.mayan.loadbalancer.server.port=8000"
      - "traefik.http.routers.mayan.rule=Host(`mayan.${DEPOT_DOMAIN_NAME}`)"
    networks:
      - mayan
      - traefik

networks:
  traefik:
    external: true
  mayan:


# todo:
# - FUSE index/volume mount - https://docs.mayan-edms.com/chapters/indexes.html?highlight=fuse
# - Set Admin password - https://github.com/mayan-edms/mayan-edms/issues/259
# - Set Watch Folder -
# - Startup /var/lib/mayan/settings folder needs to exist for local.py settings to be created
# - Documents created by www-data user, not 15000 like all other containers.
