version: "2.1"
services:
  sismics:
    image: sismics/docs
    ports:
        - "8080"
    environment:
        - DOCS_BASE_URL='http://sismics.depot.lan'
    volumes:
        - /opt/mediadepot/apps/sismics:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 1m30s
      timeout: 10s
      retries: 3
    labels:
      - "traefik.enable=true"
      - "traefik.port=8080"
      - "traefik.frontend.rule=Host:sismics.depot.lan"
      - "traefik.enable=true"
      - "traefik.http.services.sismics.loadbalancer.server.port=8080"
      - "traefik.http.routers.sismics.rule=Host(`sismics.depot.lan`)"
    networks:
      - sismics
      - traefik

  blackhole:
    image: mediadepot/sismics-importer
    environment:
      - "SISMICS_BASE_URL=http://sismics:8080"
      - "SISMICS_USERNAME=admin"
      - "SISMICS_PASSWORD=admin"
      - "PUID=15000"
      - "PGID=15000"
    volumes:
      - /media/temp/blackhole/documents:/watch
    links:
      - sismics
    depends_on:
      sismics:
        condition: service_healthy
    networks:
      - sismics

networks:
  traefik:
    external: true
  sismics:
