version: "2.1"

services:

  database:
    image: "postgres:11"
    volumes:
      - /opt/mediadepot/apps/klaxon/db:/var/lib/postgresql/data
    network_mode: bridge

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    image: "mediadepot/klaxon"
    links:
      - database
    depends_on:
      database:
        condition: service_healthy
    environment:
      RACK_ENV: "development"
      RAILS_ENV: "development"
      DATABASE_URL: "postgres://postgres@database/klaxon"
      SECRET_KEY_BASE: "secret_key_base"
    network_mode: bridge
    labels:
      - "traefik.enable=true"
      - "traefik.port=3000"
      - "traefik.frontend.rule=Host:klaxon.depot.lan"
      - "traefik.docker.network=bridge"
    volumes:
      - /opt/mediadepot/apps/klaxon/app:/config
