version: "2.1"

services:

  database:
    image: "postgres:11"
    volumes:
      - /opt/mediadepot/apps/klaxon/db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - traefik
      - klaxon
  app:
    image: "mediadepot/klaxon"
    links:
      - database
    depends_on:
      database:
        condition: service_healthy
    environment:
      RACK_ENV: "development"
      RAILS_ENV: "development"
      DATABASE_URL: "postgres://postgres@database/klaxon"
      SECRET_KEY_BASE: "secret_key_base"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.klaxon.loadbalancer.server.port=3000"
      - "traefik.http.routers.klaxon.rule=Host(`klaxon.depot.lan`)"
    volumes:
      - /opt/mediadepot/apps/klaxon/app:/config
    networks:
      - traefik
      - klaxon
networks:
  traefik:
    external: true
  klaxon:
