version: "2.1"

services:

  database:
    image: "healthcheck/postgres"
    volumes:
      - /opt/mediadepot/apps/klaxon/db:/var/lib/postgresql/data

  app:
    image: "mediadepot/klaxon"
    depends_on:
      database:
        condition: service_healthy
    environment:
      RACK_ENV: "development"
      RAILS_ENV: "development"
      DATABASE_URL: "postgres://postgres@database/klaxon"
      SECRET_KEY_BASE: "secret_key_base"
    command:
      - /bin/sh
      - -c
      - |
          bundle exec rake db:create db:migrate || true
          bundle exec rake users:create_admin || true
          bundle exec puma -C "config/puma.rb"

    labels:
      - "traefik.enable=true"
      - "traefik.port=3000"
      - "traefik.frontend.rule=Host:klaxon.depot.lan"