version: '2.2'
services:
  elasticsearch:
    image: analogj/lodestone:elasticsearch
    environment:
      #      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /opt/mediadepot/apps/lodestone/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 19200:9200
      - 19300:9300
    networks:
      - lodenet

  processor:
    image: analogj/lodestone:processor
    depends_on:
      elasticsearch:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      webapp:
        condition: service_healthy
      tika:
        condition: service_healthy
    environment:
      - LS_ELASTICSEARCH_HOST=${LS_ELASTICSEARCH_HOST:-elasticsearch}
      - LS_ELASTICSEARCH_PORT=${LS_ELASTICSEARCH_PORT:-9200}
      - LS_RABBITMQ_HOST=${LS_RABBITMQ_HOST:-rabbitmq}
      - LS_RABBITMQ_PORT=${LS_RABBITMQ_PORT:-5672}
      - LS_API_HOST=${LS_API_HOST:-webapp}
      - LS_API_PORT=${LS_API_PORT:-3000}
      - LS_TIKA_HOST=${LS_TIKA_HOST:-tika}
      - LS_TIKA_PORT=${LS_TIKA_PORT:-9998}
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=minio123
      - RABBITMQ_USER=lodestone
      - RABBITMQ_PASS=lodestone
    networks:
      - lodenet
  webapp:
    image: analogj/lodestone:web
    depends_on:
      elasticsearch:
        condition: service_healthy
      storage:
        condition: service_healthy
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.lodestone.loadbalancer.server.port=3000"
      - "traefik.http.routers.lodestone.rule=Host(`lodestone.${DEPOT_DOMAIN_NAME}`)"
      - 'traefik.http.routers.lodestone.entrypoints=websecure'
      - 'traefik.http.routers.lodestone.tls.certresolver=mydnschallenge'
    environment:
      - LS_STORAGE_HOST=${LS_STORAGE_HOST:-storage}
      - LS_STORAGE_PORT=${LS_STORAGE_PORT:-9000}
      - LS_STORAGE_PATH=${LS_STORAGE_PATH:-/storage/}
      - LS_ELASTICSEARCH_HOST=${LS_ELASTICSEARCH_HOST:-elasticsearch}
      - LS_ELASTICSEARCH_PORT=${LS_ELASTICSEARCH_PORT:-9200}
      - LS_RABBITMQ_HOST=${LS_RABBITMQ_HOST:-rabbitmq}
      - LS_RABBITMQ_PORT=${LS_RABBITMQ_PORT:-5672}
      - LS_RABBITMQ_MG_HOST=${LS_RABBITMQ_MG_HOST:-rabbitmq}
      - LS_RABBITMQ_MG_PORT=${LS_RABBITMQ_MG_PORT:-15672}
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=minio123
      - RABBITMQ_USER=lodestone
      - RABBITMQ_PASS=lodestone
    networks:
      - lodenet
      - traefik

  storage:
    image: analogj/lodestone:storage
    depends_on:
      rabbitmq:
        condition: service_healthy
    #    ports:
    #      # this port is only necessary if you would like to view the admin backend for minio. MINIO_BROWSER=off must be commented out
    #      - 9000:9000
    volumes:
      - /media/storage/documents/:/data/
    environment:
      - MINIO_USERNAME=minio
      - MINIO_GROUPNAME=minio
      - MINIO_PUID=15000
      - MINIO_PGID=15000
      - MINIO_BROWSER=off
      - LS_RABBITMQ_HOST=${LS_RABBITMQ_HOST:-rabbitmq}
      - LS_RABBITMQ_PORT=${LS_RABBITMQ_PORT:-5672}
      - RABBITMQ_USER=lodestone
      - RABBITMQ_PASS=lodestone
      - MINIO_BROWSER=off
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=minio123
    #      - MINIO_WORM=on
    networks:
      - lodenet

  rabbitmq:
    image: analogj/lodestone:rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=lodestone
      - RABBITMQ_DEFAULT_PASS=lodestone
    volumes:
      - /opt/mediadepot/apps/lodestone/rabbitmq:/var/lib/rabbitmq
    networks:
      - lodenet
  tika:
    image: analogj/lodestone:tika
    networks:
      - lodenet
networks:
  traefik:
    external: true
  lodenet:
